name: Sync Fork

on:
  schedule:
    # 每天凌晨 1 点（UTC 时间）运行一次
    - cron: '0 1 * * *'
  workflow_dispatch:
    # 允许手动触发此工作流

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout fork repository
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Add upstream repository
      run: git remote add upstream https://github.com/coolsnowwolf/lede.git

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout master
        git merge upstream/master
        git push origin master
